# Generated by Django 5.2.7 on 2025-11-06 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_disciplina_professor_turma_disciplinas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='departamento',
            new_name='situacao',
        ),
    ]
